version: '3'
services:
  kafka:
    image: blacktop/kafka:2.6
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: to-test
  postgres-test:
    image: postgres:11-alpine
    ports:
      - 5436:5432
    volumes:
      - ~/.system_check_postgres_test:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dydxserver123
      POSTGRES_USER: dydx_test
  postgres:
    image: postgres:11-alpine
    ports:
      - 5435:5432
    volumes:
      - ~/.system_check_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dydxserver123
      POSTGRES_USER: dydx_dev
  redis:
    image: redis:5.0.6-alpine
    ports:
      - 6382:6379
